// Ultra-comprehensive India cities dataset
// Covers all district HQs, talukas, tehsils, census towns for all 28 states + 8 UTs

export const INDIA_STATES = [
  {
    state: 'Andhra Pradesh',
    cities: [
      'Visakhapatnam','Vijayawada','Guntur','Nellore','Kurnool','Rajahmundry','Tirupati','Kakinada',
      'Kadapa','Anantapur','Eluru','Ongole','Nandyal','Srikakulam','Bhimavaram','Machilipatnam',
      'Adoni','Tenali','Proddatur','Chittoor','Hindupur','Madanapalle','Tadepalligudem','Chilakaluripet',
      'Yemmiganur','Kadiri','Srikalahasti','Tanuku','Narasaraopet','Vizianagaram','Guntakal',
      'Dharmavaram','Gudivada','Amalapuram','Tadipatri','Naidupeta','Rajam','Bapatla','Palasa',
      'Rayachoti','Punganur','Jaggampeta','Salur','Bobbili','Palakonda','Narasannapeta','Parvathipuram',
      'Tekkali','Amadalavalasa','Narasapuram','Palakollu','Narsapur','Bheemunipatnam','Anakapalle',
      'Narsipatnam','Paderu','Araku','Kovvur','Rajole','Mandapeta','Pithapuram','Samalkot',
      'Tuni','Golugonda','Rampachodavaram','Addanki','Chimakurthy','Chirala','Vetapalem',
      'Kandukur','Podili','Markapur','Giddalur','Kanigiri','Kavali','Atmakur','Vinukonda',
      'Sattenapalle','Piduguralla','Gurazala','Macherla','Narasaraopet','Tadepalle','Mangalagiri',
      'Ponnur','Repalle','Bapatla','Vemuru','Nizampatnam','Mopidevi','Kolluru','Kodali',
      'Amaravati','Ibrahimpatnam','Jagannadhapuram','Mylavaram','Tiruvuru','Nuzvid','Chandarlapadu',
      'Kaikalur','Pedana','Bantumilli','Bhattiprolu','Pamarru','Pamidimukkala','Kankipadu',
      'Gannavaram','Vuyyuru','Nandigama','Tiruvuru','Jaggayyapeta','Nalanda','Penamaluru',
      'Patamata','Unguturu','Denduluru','Nidadavole','Gopalapuram','Tangellamudi','Polavaram',
      'Devarapalli','Kovvur','Narsapur','Buttayagudem','Jangareddygudem','Tadepalligudem','Akividu',
      'Palakollu','Bhimadole','Chintalapudi','Ganapavaram','Lingapalem','Mudinepalle','Powerpet',
      'Tiruvuru','Ibrahimpatnam','Mylavaram','Kondapalli','Vjaywada','Pedapudi','Peddapuram',
      'Uppala','Kotturu','Rajam','Narasannapeta','Sompeta','Ichchapuram','Kaviti',
      'Mandasa','Regidi','Ranasthalam','Etcherla','Saravakota','Hiramandalam','Pathapatnam',
      'Meliaputti','Rayagada','Kotabommali','Palakonda','Bhamini','Parvathipuram','Kurupam'
    ]
  },
  {
    state: 'Arunachal Pradesh',
    cities: [
      'Itanagar','Naharlagun','Pasighat','Tawang','Ziro','Bomdila','Tezu','Along','Roing',
      'Khonsa','Changlang','Daporijo','Yingkiong','Anini','Seppa','Namsai','Basar','Aalo',
      'Longding','Deomali','Miao','Jairampur','Nampong','Manmao','Wakro','Lekhi','Banderdewa',
      'Nirjuli','Chimpu','Gohpur','Bhalukpong','Tipi','Kalaktang','Dirang','Tawang','Jang',
      'Lumla','Zemithang','Kurung Kumey','Koloriang','Nyapin','Palin','Potin','Sangram',
      'Yangte','Boleng','Mariyang','Jengging','Mebo','Ruksin','Nari','Likabali','Sago',
      'Bame','Tirbin','Darak','Paya','Geku','Tuting','Kamba','Mechuka','Monigong'
    ]
  },
  {
    state: 'Assam',
    cities: [
      'Guwahati','Silchar','Dibrugarh','Jorhat','Nagaon','Tinsukia','Tezpur','Bongaigaon',
      'Dhubri','North Lakhimpur','Karimganj','Sivasagar','Goalpara','Barpeta','Mangaldoi',
      'Diphu','Golaghat','Hailakandi','Hojai','Lanka','Lumding','Mariani','Nalbari','Rangia',
      'Margherita','Marigaon','Dhekiajuli','Tihu','Kokrajhar','Haflong','Gossaigaon','Bilasipara',
      'Gauripur','Golakganj','Mankachar','Krishnai','Dudhnoi','Matia','Jaleswar','Rongjeng',
      'Resubelpara','Baghmara','Nongstoin','Phulbari','Mendipather','Halakura','Badarpur',
      'Sonai','Lakhipur','Jiribam','Algapur','Boitamari','Sidli','Kajalgaon','Bijni','Abhayapuri',
      'Bongaigaon','Dotma','Baghbor','Sorbhog','Tihu','Nalbari','Tamulpur','Mukalmua',
      'Pathsala','Barpeta Road','Chenga','Sarukhetri','Howly','Barkhetri','Chamaria','Pub Barpeta',
      'Sarthebari','Sualkuchi','Hajo','Rampur','Goreswar','Sontoli','Runikhata','Rowta',
      'Kalaigaon','Sipajhar','Khoirabari','Jagiroad','Laharighat','Dhing','Kaliabor','Bokakhat',
      'Dergaon','Sarupathar','Sankardev','Furkating','Titabor','Jorhat','Teok','Majuli',
      'Nimatighat','Simaluguri','Demow','Sonari','Naharkatia','Duliajan','Digboi','Ledo',
      'Doom Dooma','Tinsukia','Sadiya','Moran','Dibrugarh','Chabua','Lahoal','Namrup',
      'Doomdooma','Kakopathar','Bordumsa','Joypur','Namsang','Simlaguri','Bihpuria',
      'Dhemaji','Jonai','Murkong Selek','Dihing','Sadia','Mekela','Charaideo'
    ]
  },
  {
    state: 'Bihar',
    cities: [
      'Patna','Gaya','Bhagalpur','Muzaffarpur','Darbhanga','Arrah','Bihar Sharif','Begusarai',
      'Katihar','Munger','Purnia','Saharsa','Hajipur','Sasaram','Dehri','Siwan','Motihari',
      'Nawada','Bagaha','Buxar','Kishanganj','Sitamarhi','Jamalpur','Jehanabad','Aurangabad',
      'Lakhisarai','Madhubani','Samastipur','Supaul','Araria','Chapra','Bettiah','Gopalganj',
      'Khagaria','Madhepura','Sheikhpura','Sheohar','Vaishali','Banka','Jamui','Kaimur',
      'Nalanda','Rohtas','Saran','Barh','Mokama','Hilsa','Bikram','Masaurhi','Danapur',
      'Fatuha','Khusrupur','Belchi','Pandarak','Phulwarisharif','Bakhtiyarpur','Barnaul',
      'Rajgir','Islampur','Biharsharif','Giriyak','Sarmera','Asthawan','Bind','Harnaut',
      'Katrisarai','Silao','Ben','Ekangarsarai','Tharthari','Chandi','Rahui','Noorsarai',
      'Wazirganj','Parwalpur','Karait','Khanpur','Kaspa','Giriyak','Biharsharif','Har',
      'Bela','Sohsarai','Unchagaon','Nalanda','Naubatpur','Punpun','Bihta','Neora',
      'Maner','Phulwari','Naubatpur','Bichhiya','Belchhi','Khizarsarai','Pawapuri','Giriyak',
      'Sultanganj','Kahalgaon','Pirpainti','Naugachia','Gopalpur','Sabour','Banka','Dhuraiya',
      'Amarpur','Barahat','Banka','Bounsi','Katoria','Dhamdaha','Kursela','Manihari','Korha',
      'Manihri','Barari','Gopalpur','Sultanganj','Banka','Amba','Bishambharpur','Simaria'
    ]
  },
  {
    state: 'Chhattisgarh',
    cities: [
      'Raipur','Bhilai','Korba','Bilaspur','Durg','Rajnandgaon','Jagdalpur','Ambikapur',
      'Chirmiri','Dhamtari','Mahasamund','Raigarh','Kanker','Kawardha','Mungeli','Janjgir',
      'Champa','Dongargarh','Naila','Sakti','Tilda','Bemetara','Baloda Bazar','Gariaband',
      'Balod','Bijapur','Dantewada','Sukma','Kondagaon','Narayanpur','Surajpur','Balrampur',
      'Jashpur','Koriya','Baikunthpur','Manendragarh','Pendra','Lormi','Takhatpur','Bilha',
      'Masturi','Kota','Pali','Sipat','Ratanpur','Mungeli','Patharia','Beltara','Gaurella',
      'Pendra','Marwahi','Katghora','Pali','Dipka','Gevra','Kartala','Kusmunda','Darri',
      'Chirimiri','Manendragarh','Korea','Baikunthpur','Ramanujganj','Wadrafnagar','Pratappur',
      'Ambikapur','Sitapur','Mainpat','Odgi','Rajpur','Bhaiyathan','Premnagar','Lundra',
      'Surajpur','Balrampur','Kunkuri','Jashpur','Bagicha','Pathalgaon','Bharatpur','Raigarh',
      'Sarangarh','Gharghoda','Lailunga','Kharsia','Saria','Pusaur','Dharmjaigarh','Koida',
      'Dongargaon','Bodla','Deobhog','Mainpur','Rajim','Phingeshwar','Gariaband','Devapur',
      'Kawardha','Pandariya','Bodla','Sahaspur Lohara','Bemetara','Nandini','Berla','Saja',
      'Dhamtari','Kurud','Nagri','Sihawa','Baloda','Bansikala','Bindranawagarh','Kanker',
      'Antagarh','Bhanupratappur','Dantewada','Konta','Bijapur','Bhairamgarh','Narayanpur'
    ]
  },
  {
    state: 'Goa',
    cities: [
      'Panaji','Margao','Vasco da Gama','Mapusa','Ponda','Bicholim','Curchorem','Sanquelim',
      'Canacona','Quepem','Pernem','Valpoi','Cuncolim','Calangute','Candolim','Anjuna',
      'Baga','Colva','Benaulim','Agonda','Palolem','Arambol','Vagator','Morjim','Assagao',
      'Aldona','Moira','Saligao','Pilerne','Penha de França','Porvorim','Taleigao','Bambolim',
      'Dona Paula','Miramar','Caculo','St Cruz','Curca','Goa Velha','Cortalim','Sancoale',
      'Mormugao','Baina','Bogmalo','Cansaulim','Arossim','Majorda','Betalbatim','Colva',
      'Mobor','Betul','Cuncolim','Navelim','Cavelossim','Chandor','Loutolim','Nuvem',
      'Raia','Curtorim','Fatorda','Aquem','Monte','Arpora','Kadamba','Shiroda','Dharbandora',
      'Usgaon','Ponda','Curti','Tisk','Marcela','Farmagudi','Khandepar','Savoi Verem',
      'Sattari','Rivona','Sanguem','Collem','Molem','Mollem','Castlerock','Braganza'
    ]
  },
  {
    state: 'Gujarat',
    cities: [
      'Ahmedabad','Surat','Vadodara','Rajkot','Bhavnagar','Jamnagar','Gandhinagar','Junagadh',
      'Anand','Navsari','Morbi','Nadiad','Surendranagar','Bharuch','Mehsana','Porbandar',
      'Godhra','Palanpur','Valsad','Amreli','Bhuj','Veraval','Gondal','Vapi','Botad',
      'Patan','Deesa','Jetpur','Sidhpur','Wadhwan','Dhoraji','Mandvi','Visnagar','Khambhat',
      'Kalol','Petlad','Ankleshwar','Una','Talaja','Bardoli','Kapadvanj','Lunavada','Modasa',
      'Himatnagar','Dahod','Jhalod','Idar','Khambhalia','Salaya','Dwarka','Mangrol',
      'Keshod','Upleta','Jamjodhpur','Rajula','Mahuva','Palitana','Ghogha','Sihor',
      'Gariadhar','Gadhada','Vallabhipur','Umrala','Savarkundla','Lathi','Jafrabad',
      'Kodinar','Visavadar','Keshod','Mangrol','Bantva','Vanthali','Mendarda','Bhesan',
      'Talala','Chorwad','Sutrapada','Veraval','Patan Somnath','Gir Somnath','Una',
      'Dhari','Bagasara','Khirasara','Rajula','Jariya','Kukavav','Vadiya','Khambha',
      'Lilia','Khirasra','Babra','Gadhakda','Hadmatiya','Amrapur','Vadhvan','Joravarnagar',
      'Muli','Chotila','Thangadh','Halvad','Patdi','Dhrangadhra','Limbdi','Lakhtar',
      'Sayla','Chuda','Dasada','Viramgam','Sanand','Dholka','Dhandhuka','Bavla','Nal',
      'Bagodara','Dhanduka','Wasna','Mahemdabad','Thasra','Balasinor','Umreth','Virpur',
      'Meghraj','Dhansura','Bayad','Mansa','Kadi','Unjha','Satlasana','Kheralu','Vadnagar',
      'Patan','Chanasma','Harij','Radhanpur','Sankheshwar','Thara','Jalore','Vav','Tharad',
      'Dhanera','Danta','Amirgadh','Vadgam','Palanpur','Deodar','Kankrej','Panthawada',
      'Bhabhar','Suigam','Sami','Patan','Harij','Chanasma','Radhanpur','Sankheshwar',
      'Lakhani','Vagad','Mahesana','Kadi','Unjha','Vijapur','Bechraji','Jagudan',
      'Kukarwada','Satlasana','Kheralu','Vadnagar','Sidhpur','Patan','Visanagar',
      'Kheda','Mahudha','Galteshwar','Kathlal','Matar','Anand','Petlad','Sojitra',
      'Borsad','Tarapur','Cambay','Khambhat','Dabhan','Vasad','Karamsad','Anklav',
      'Umreth','Balasinor','Thasra','Mahisa','Kapadvanj','Kathlal','Vagharoli',
      'Bharuch','Amod','Jambusar','Vagra','Jhagadia','Anklesvar','Hansot','Olpad',
      'Mangrol','Mandvi','Bardoli','Vyara','Valod','Nizar','Songadh','Mangrol',
      'Uchhhal','Nichlaul','Kawant','Nasvadi','Chhota Udaipur','Sankheda','Dabhoi',
      'Padra','Desar','Waghodia','Sinor','Karjan','Desar','Makarpura','Manjalpur',
      'Akota','Fatehganj','Savli','Bajwa','Halol','Shehera','Godhra','Lunawada',
      'Kadana','Santrampur','Khanpur','Jhalod','Dahod','Devgadh Baria','Ghoghamba',
      'Piplod','Limkheda','Fatepura','Sanjeli','Dhanpur','Zalod','Morva Hadaf'
    ]
  },
  {
    state: 'Haryana',
    cities: [
      'Faridabad','Gurugram','Panipat','Ambala','Yamunanagar','Rohtak','Hisar','Karnal',
      'Sonipat','Panchkula','Bhiwani','Sirsa','Bahadurgarh','Jind','Thanesar','Kaithal',
      'Palwal','Rewari','Narnaul','Fatehabad','Pehowa','Kalka','Kurukshetra','Charkhi Dadri',
      'Hansi','Tohana','Narwana','Mahendragarh','Jhajjar','Pundri','Safidon','Gohana',
      'Ratia','Ladwa','Shahbad','Pinjore','Ganaur','Naraingarh','Asandh','Mandi Dabwali',
      'Adampur','Barwala','Uklana','Uchana','Ellenabad','Dabwali','Rania','Kalanwali',
      'Nathusari Chopta','Bhattu Kalan','Jakhal','Tohana','Fatehabad','Bhuna','Bansbari',
      'Balsamand','Narnaund','Hansi','Hisar','Barwala','Adampur','Agroha','Uklana',
      'Siwan','Kasni','Loharu','Bahadurgarh','Jhajjar','Machhrauli','Matanhail','Palhawas',
      'Beri','Badli','Pataudi','Sohna','Taoru','Nuh','Punhana','Ferozepur Jhirka',
      'Hathin','Hodal','Aurangabad','Hassanpur','Palwal','Prithla','Hodel','Sikandarpur',
      'Ballabgarh','Tigaon','Old Faridabad','Mewat','Rewari','Dharuhera','Bawal','Kosli',
      'Palhawas','Jahazgarh','Nahar','Khol','Majra','Bhiwani','Loharu','Siwani','Behal',
      'Tosham','Kairu','Bawani Khera','Bahal','Jhojhu','Dulheri','Mandola','Shikarpur',
      'Kharkhoda','Rai','Rajlupgar','Ganaur','Murthal','Kundli','Samalkha','Panipat',
      'Israna','Madlauda','Karna','Taraori','Assandh','Nilokheri','Gharaunda','Nissing',
      'Indri','Kunj Pura','Rasulpur','Bastara','Shahabad Markanda','Ladwa','Babain',
      'Kaithal','Pundri','Cheeka','Kalayat','Siwan','Guhla','Rajaund','Dhand',
      'Kurukshetra','Pehowa','Thanesar','Babain','Shahbad','Ladwa','Ismailabad','Pipli',
      'Jind','Julana','Safidon','Narwana','Pillukheda','Uchana','Alewa','Prao'
    ]
  },
  {
    state: 'Himachal Pradesh',
    cities: [
      'Shimla','Solan','Dharamshala','Mandi','Palampur','Baddi','Nahan','Paonta Sahib',
      'Sundarnagar','Chamba','Una','Kullu','Manali','Bilaspur','Hamirpur','Kasauli',
      'Nalagarh','Rampur','Rohru','Theog','Kangra','Nurpur','Jawali','Indora',
      'Jogindernagar','Sarkaghat','Karsog','Kotkhai','Arki','Renuka','Rajgarh',
      'Sirmaur','Pachhad','Shillai','Nohra','Sangrah','Nankhari','Nichar','Pooh',
      'Spiti','Kaza','Losar','Kibber','Key','Pin','Dhankar','Nako','Sumdo',
      'Lahaul','Keylong','Udaipur','Tindi','Sissu','Chatru','Rohtang','Solang',
      'Manali','Vashisht','Naggar','Banjar','Ani','Nirmand','Janjehli','Thunag',
      'Kulu','Bhuntar','Kasol','Manikaran','Parvati','Pulga','Tosh','Kheerganga',
      'Bajaura','Khokhan','Chowai','Gada Gushaini','Larji','Sainj','Katgaon',
      'Dharamshala','McLeod Ganj','Baijnath','Palampur','Chamunda','Bir','Billing',
      'Rajgundha','Ghatasani','Tashi Jong','Dharamkot','Bhagsu','Sidhpur','Khara Danda',
      'Kangra','Nurpur','Nagrota Bagwan','Shahpur','Dehra','Jawali','Jawali','Fatehpur',
      'Hamirpur','Barsar','Bhoranj','Sujanpur','Nadaun','Tira Sujanpur','Tauni Devi',
      'Bijhari','Bamsan','Bhota','Jahu','Una','Bangana','Haroli','Mehatpur','Amb',
      'Chintpurni','Jawali','Gagret','Ghanaur','Nangal','Solha','Tahliwal','Daulatpur',
      'Chamba','Churah','Pangi','Tissa','Bharmour','Holi','Saho','Kharamukh',
      'Bilaspur','Ghummiarwin','Jhanduta','Swarghat','Ghumarwin','Berthin','Lathiani',
      'Solan','Kasauli','Parwanoo','Baddi','Barotiwala','Nalagarh','Arki','Dharampur',
      'Kandaghat','Chail','Naldehra','Mashobra','Kufri','Narkanda','Fagu','Jubbal',
      'Rohru','Kotkhai','Chirgaon','Rampur','Jeori','Nichar','Peo','Moorang','Hangrang'
    ]
  },
  {
    state: 'Jharkhand',
    cities: [
      'Ranchi','Jamshedpur','Dhanbad','Bokaro','Deoghar','Phusro','Hazaribagh','Giridih',
      'Ramgarh','Medininagar','Chirkunda','Mihijam','Jugsalai','Chakradharpur','Chaibasa',
      'Gumla','Lohardaga','Latehar','Simdega','Khunti','Sahebganj','Pakur','Godda',
      'Dumka','Jamtara','Koderma','Chatra','Garhwa','Palamu','Seraikela','Kharsawan',
      'Adityapur','Gamharia','Mango','Jugsalai','Jharia','Sindri','Katras','Nirsa',
      'Kenduadih','Sijua','Rajdhanwar','Tisri','Birni','Bagodar','Pirtand','Dumri',
      'Dhanwar','Bermo','Ramgarh Cantonment','Mandu','Gola','Ormanjhi','Mandar',
      'Angara','Sonahatu','Silli','Bundu','Tamar','Raidih','Bero','Chanho','Lapung',
      'Namkum','Kanke','Hatia','Hesag','Ormanjhi','Bariatu','Doranda','Hinoo',
      'Kokar','Lalpur','Morabadi','Ratu','Tupudana','Itki','Nagri','Getalsud',
      'Barkagaon','Ichak','Tandwa','Hunterganj','Pratappur','Simaria','Kunda',
      'Sadar','Gidhaur','Mandu','Chouparan','Barkatha','Churchu','Topchanchi',
      'Govindpur','Dhanbad','Mugma','Baliapur','Purnapani','Babupara','Tisra',
      'Baghmara','Jogta','Maithon','Panchet','Chas','Bokaro','Chandankiyari',
      'Topchanchi','Gomoh','Petarwar','Bermo','Ramgarh','Patratu','Barkakana',
      'Mandu','Phusro','Jaridih','Balidih','Bokaro Steel City','Chas','Gomia',
      'Tenu Dam','Nawadih','Dugda','Peterbar','Chandrapura','Khalari','Huntergunj'
    ]
  },
  {
    state: 'Karnataka',
    cities: [
      'Bengaluru','Mysuru','Mangaluru','Hubli','Dharwad','Belgaum','Davanagere','Bellary',
      'Bijapur','Shimoga','Tumkur','Raichur','Bidar','Udupi','Gulbarga','Hassan',
      'Hospet','Gadag','Bagalkot','Chitradurga','Mandya','Chikmagalur','Kolar',
      'Robertsonpet','Gangavati','Ranebennuru','Chikkaballapur','Sirsi','Ranibennur',
      'Karwar','Sagara','Sira','Madikeri','Puttur','Sankeshwar','Mulbagal',
      'Channapatna','Kollegal','Ramanagara','Nelamangala','Chamarajanagar','Yadgir',
      'Koppal','Haveri','Vijayapura','Kalaburagi','Bagepalli','Gauribidanur',
      'Gudibanda','Gudibanda','Chintamani','Sidlaghatta','Chickballapur','Gowribidanur',
      'Devanahalli','Doddaballapur','Anekal','Hoskote','Malur','Srinivaspur',
      'Bangarapet','Kolar Gold Fields','Bangarpet','Bethamangala','Mulbagal',
      'Pavagada','Madhugiri','Koratagere','Tiptur','Gubbi','Turuvekere','Kunigal',
      'Tumkur','Sira','Holalkere','Molakalmuru','Hiriyur','Challakere','Hosadurga',
      'Chitradurga','Channagiri','Jagalur','Harihar','Ranebennuru','Byadgi',
      'Shiggaon','Hangal','Savanur','Haveri','Bankapur','Rattihalli','Hirekerur',
      'Dundasi','Devagiri','Hubli','Kundgol','Dharwad','Kalghatgi','Navalagund',
      'Navalgund','Annigeri','Ron','Gadag','Nargund','Shirhatti','Lakshmeshwara',
      'Mundaragi','Gajendragad','Srirangapatna','Pandavapura','Kirugavalu','Nagamangala',
      'Bellur','Malavalli','Maddur','Mahadevapura','Krishnarajanagara','Mandya',
      'Melukote','Kadur','Tarikere','Birur','Mudigere','Koppa','Sringeri','Narasimharajapura',
      'Ajjampura','Kudligi','Harapanahalli','Honnali','Channagiri','Jagalur','Harihara',
      'Bhadravathi','Shimoga','Soraba','Thirthahalli','Hosanagara','Sagar','Shivamogga',
      'Jewargi','Shorapur','Yadgir','Shahpur','Gurmatkal','Chittapur','Sedam',
      'Chincholi','Kalaburagi','Afzalpur','Aland','Chittapur','Gulbarga','Basavakalyan',
      'Bidar','Humnabad','Bhalki','Aurad','Basavakalyan','Kamalnagar','Baidyanath',
      'Muddebihal','Sindagi','Indi','Muddebihal','Vijayapura','Bijapur','Hungund',
      'Badami','Ilkal','Bagalkot','Jamkhandi','Mudhol','Bilagi','Lokapur','Mahalingpur',
      'Kaladgi','Rabkavi','Banhatti','Guledgudda','Gajendragada','Mundargi','Shirahatti',
      'Bellary','Hospet','Kudligi','Harapanahalli','Sandur','Kampli','Siraguppa',
      'Raichur','Manvi','Devadurga','Lingasugur','Sindhnur','Mudgal','Maski',
      'Lingsugur','Gangavathi','Koppal','Yelbarga','Kushtagi','Kustagi','Karatagi',
      'Munirabad','Hosapete','Bellary','Siruguppa','Haveri','Ranibennur','Hirekerur',
      'Byadgi','Akkialur','Shiggaon','Hangal','Savanur','Karkala','Kundapura',
      'Udupi','Brahmavar','Byndoor','Kaup','Mangalore','Bantwal','Belthangady',
      'Puttur','Sullia','Madikeri','Virajpet','Somwarpet','Kushalnagar','Napoklu',
      'Piriyapatna','Kushalnagar','Hunsur','Periyapatna','Mysuru','Nanjangud',
      'Chamarajanagar','Kollegal','Yelandur','Hanur','Gundlupet','Madikeri','Kadaba',
      'Dharmasthala','Uppinangady','Naravi','Vitla','Bantwal','Beltangady','Puttur',
      'Hassan','Alur','Arkalgud','Arasikere','Belur','Channarayapatna','Holenarasipur',
      'Sakleshpur','Gundlupet','Hunasur','Holenarsipur','Arsikere','Belur','Turuvekere',
      'Tiptur','Sira','Gubbi','Kunigal','Koratagere','Madhugiri','Pavagada','Chikkaballapur',
      'Sidlaghatta','Chintamani','Gauribidanur','Bagepalli','Doddaballapur','Devanahalli',
      'Hosakote','Anekal','Kanakapura','Ramanagara','Channapatna','Magadi','Kunigal'
    ]
  },
  {
    state: 'Kerala',
    cities: [
      'Thiruvananthapuram','Kochi','Kozhikode','Thrissur','Kannur','Kollam','Palakkad',
      'Alappuzha','Malappuram','Irinjalakuda','Vatakara','Kanhangad','Taliparamba',
      'Thodupuzha','Kasaragod','Ponnani','Chalakudy','Changanacherry','Punalur',
      'Nedumangad','Kottayam','Pathanamthitta','Idukki','Wayanad','Manjeri','Kayamkulam',
      'Neyyattinkara','Cherthala','Perinthalmanna','Tirur','Guruvayoor','Muvattupuzha',
      'Adoor','Mavelikkara','Attingal','Payyannur','Koyilandy','Ottapalam','Shoranur',
      'Cherpulassery','Kunnamkulam','Pala','Ettumanoor','Kanjirappally','Peermedu',
      'Mundakayam','Erattupetta','Ranni','Pandalam','Chengannur','Thiruvalla',
      'Haripad','Ambalapuzha','Aroor','Cherthala','Kuttanad','Mannar','Mavelikara',
      'Muhamma','Chambakulam','Pathiramanal','Kainakary','Pulincunnoo','Thanneermukkom',
      'Vaikom','Ettumanoor','Changanacherry','Kottayam','Ernakulam','Kakkanad',
      'Kalamassery','Aluva','Perumbavoor','Kothamangalam','Muvattupuzha','Piravom',
      'Angamaly','Manarcaud','Parappanangadi','Tirur','Tirurangadi','Kondotty',
      'Malappuram','Manjeri','Perinthalmanna','Mannarkkad','Palakkad','Chittur',
      'Ottapalam','Pattambi','Shornur','Guruvayur','Thrissur','Kodungallur',
      'Irinjalakuda','Chalakudy','Mukundapuram','Chavakkad','Kunnamkulam','Trichur',
      'Wadakkanchery','Thrissur','Manalur','Vellangallur','Pavaratty','Chalissery',
      'Mullankkunnathukavu','Ollukkara','Chelakkara','Cherpu','Mulanthuruthy','Piravom',
      'Thrikkakara','Kalamassery','Ernakulam','Fort Kochi','Mattancherry','Palluruthy',
      'Thrikkovilvattom','Cheranelloor','Thrippunithura','Aroor','Kundannoor','Maradu',
      'Eloor','Alwaye','Nedumbassery','Perumbavoor','Neriamangalam','Kothamangalam',
      'Thodupuzha','Munnar','Devikulam','Udumbanchola','Adimali','Azhutha','Kattappana',
      'Peerumade','Vandenmedu','Cardamom Hills','Kumily','Thekkady','Vagamon','Painavu',
      'Kozhencherry','Ranni','Konni','Aranmula','Thiruvalla','Mallappally','Ezhamkulam',
      'Pandalam','Chengannur','Mannar','Mylapra','Pramadom','Seethathode','Perinad',
      'Kottarakara','Punalur','Pathanapuram','Chadayamangalam','Anchal','Plachicottah',
      'Neduvathur','Mukhathala','Ittiva','Kulathupuzha','Oachira','Karunagappally',
      'Chathanoor','Karikode','Paravur','Ashtamudi','Kollam','Kundara','Ezhukone',
      'Kadakkal','Sasthamkotta','Ayoor','Thenmala','Nedumangad','Varkala','Attingal',
      'Chirayinkeezhu','Parassala','Vellanad','Vilavocode','Kattakada','Pothencode',
      'Sreekaryam','Kazhakuttom','Technopark','Peroorkada','Kudappanakunnu','Kowdiar',
      'Palayam','Chalai','Thampanoor','Thiruvananthapuram','Neyyattinkara','Balaramapuram',
      'Aruvikkara','Kizhuvilam','Perumkadavila','Pazhayakunnummel','Kuttichal'
    ]
  },
  {
    state: 'Madhya Pradesh',
    cities: [
      'Bhopal','Indore','Jabalpur','Gwalior','Ujjain','Sagar','Dewas','Satna','Ratlam',
      'Rewa','Murwara','Singrauli','Burhanpur','Khandwa','Bhind','Chhindwara','Guna',
      'Shivpuri','Vidisha','Chhatarpur','Damoh','Mandsaur','Khargone','Neemuch',
      'Pithampur','Hoshangabad','Itarsi','Sehore','Betul','Seoni','Balaghat',
      'Datia','Mhow','Nagda','Tikamgarh','Ashok Nagar','Sidhi','Shahdol','Anuppur',
      'Umaria','Katni','Panna','Raisen','Harda','Dindori','Mandla','Narsinghpur',
      'Niwari','Maihar','Jaora','Sanchi','Gyaraspur','Begumganj','Pachmarhi',
      'Pipariya','Sohagpur','Bankhedi','Babai','Kasrawad','Barwani','Rajpur',
      'Sendhwa','Pandhana','Bhikangaon','Niwali','Anjad','Maheshwar','Badwaha',
      'Mandleshwar','Dharampuri','Mhow','Depalpur','Sanwer','Hatod','Rau',
      'Kanadiya','Simrol','Manpur','Kalapipal','Shujalpur','Shajapur','Agar',
      'Susner','Nalkheda','Berchha','Maksi','Barod','Sehore','Budhni','Nasrullaganj',
      'Shahganj','Ashta','Ichhawar','Rehti','Shyampur','Raisen','Badi','Bareli',
      'Silwani','Umariya','Obaidullaganj','Mandideep','Nateran','Ganj Basoda',
      'Kurwai','Sanchi','Lateri','Begumganj','Damoh','Jabera','Hatta','Patera',
      'Pathariya','Banda','Chhatarpur','Buxwaha','Rajnagar','Bijawar','Harpalpur',
      'Lavkushnagar','Panna','Ajaigarh','Pawai','Shahnagar','Sohagpur','Deohara',
      'Amanganj','Rewa','Teonthar','Mauganj','Naigarhi','Sirmaur','Banikala',
      'Rampur Naikin','Devtalab','Sirmour','Citrauta','Mangawa','Teohari',
      'Satna','Maihar','Nagod','Rampur Baghelan','Unchehra','Amarpatan','Raipur Karchulian',
      'Shahdol','Jaisingnagar','Burhar','Sohagpur','Beohari','Jaitpur','Kotma',
      'Anuppur','Pushprajgarh','Rajendragram','Amarkantak','Umaria','Bandhavgarh',
      'Manpur','Khandwa','Khirkiya','Harsud','Punasa','Khalwa','Pandhana','Bagud',
      'Betul','Sarni','Shahpur','Bhainsdehi','Multai','Amla','Bharweli','Chiraidongri',
      'Chicholi','Athner','Prabhat Pattan','Chhindwara','Sausar','Pandhurna','Nagpur',
      'Jamai','Amarwara','Chaurai','Harrai','Tamia','Bichhua','Mohgaon','Seoni',
      'Keolari','Barghat','Ghansore','Lakhnadon','Chhapara','Manegaon','Kurai',
      'Balaghat','Waraseoni','Katangi','Lanji','Paraswada','Baihar','Birsa','Kirnapur',
      'Kanhiwara','Mandla','Niwas','Mawai','Narayanganj','Bichhiya','Ghughari',
      'Dindori','Shahpura','Mehandwani','Bajag','Karanjia','Samnapur'
    ]
  },
  {
    state: 'Maharashtra',
    cities: [
      // Mumbai Metropolitan Region
      'Mumbai','Navi Mumbai','Thane','Kalyan','Dombivali','Ulhasnagar','Ambernath',
      'Badlapur','Karjat','Khopoli','Panvel','Raigad','Alibag','Pen','Roha','Mahad',
      'Murud','Shrivardhan','Mangaon','Poladpur','Tala','Mhasla','Sudhagad',
      // Pune Division
      'Pune','Pimpri-Chinchwad','Solapur','Satara','Sangli','Kolhapur','Baramati',
      'Chakan','Talegaon Dabhade','Rajgurunagar','Khed','Shirur','Daund','Indapur',
      'Bhor','Velhe','Mulshi','Maval','Haveli','Phaltan','Wai','Mahabaleshwar',
      'Panchgani','Karad','Koregaon','Khandala','Lonand','Tasgaon','Miraj',
      'Jat','Vita','Kavathe Mahankal','Atpadi','Walwa','Shirala','Khanapur','Barshi',
      'Pandharpur','Karmala','Madha','Mohol','Akkalkot','Malshiras','Sangole','Maan',
      // Nashik Division
      'Nashik','Malegaon','Dhule','Jalgaon','Nandurbar','Manmad','Yeola','Nandgaon',
      'Niphad','Sinnar','Igatpuri','Trimbak','Kalwan','Dindori','Surgana','Peint',
      'Baglan','Satana','Chandwad','Deola','Kopargaon','Shrirampur','Rahuri',
      'Sangamner','Akole','Parner','Pathardi','Shevgaon','Karjat','Jamkhed',
      'Shrigonda','Rahata','Newasa','Nevasa','Erandol','Bhusawal','Chalisgaon',
      'Pachora','Amalner','Parola','Dharangaon','Jamner','Raver','Yawal','Chopda',
      'Muktainagar','Shahada','Taloda','Navapur','Akkalkuwa','Akrani','Shirpur',
      // Aurangabad Division
      'Aurangabad','Jalna','Beed','Latur','Osmanabad','Hingoli','Nanded','Parbhani',
      'Vaijapur','Paithan','Ambajogai','Georai','Ashti','Kaij','Dharur','Patoda',
      'Shirur Kasar','Wadwani','Parli','Gangakhed','Selu','Jintur','Palam','Purna',
      'Basmath','Kalamnuri','Vasmat','Aundha Nagnath','Sengaon','Loha','Mukhed',
      'Naigaon','Mudkhed','Bhokar','Kandhar','Mahur','Kinwat','Hadgaon','Himayatnagar',
      'Ardhapur','Degloor','Biloli','Dharmabad','Umarga','Tuljapur','Bhum','Paranda',
      'Washi','Kalamb','Lohara','Murum','Phulambri','Sillod','Soegaon','Kannad',
      'Khuldabad','Jafrabad','Bhokardan','Badnapur','Partur','Mantha','Ambad',
      // Amravati Division
      'Amravati','Akola','Yavatmal','Buldhana','Washim','Wardha',
      'Risod','Mangrulpir','Manora','Karanja','Murtizapur','Akot','Telhara','Balapur',
      'Patur','Daryapur','Anjangaon','Chandur Railway','Morshi','Warud','Achalpur',
      'Dharni','Chikhaldara','Khamgaon','Shegaon','Malkapur','Nandura','Mehkar',
      'Sindkhed Raja','Lonar','Deulgaon Raja','Kelapur','Pandharkawada','Ner',
      'Mahagaon','Umarkhed','Digras','Arni','Ghatanji','Zari Jamani','Wani',
      'Maregaon','Pusad','Darwha','Kalamb','Ralegaon',
      // Nagpur Division
      'Nagpur','Chandrapur','Gondia','Bhandara','Wardha','Gadchiroli',
      'Bhadravati','Brahmapuri','Saoli','Mul','Sindewahi','Nagbhid','Sironcha',
      'Etapalli','Aheri','Bhamragad','Mulchera','Korchi','Dhanora','Chamorshi',
      'Desaiganj','Armori','Kurkheda','Gondiya','Tirora','Goregaon','Arjuni Morgaon',
      'Sadak Arjuni','Salekasa','Amgaon','Deori','Lakhandur','Pauni','Mohadi',
      'Sakoli','Lakhani','Gondpipri','Pombhurna','Rajura','Korpana','Jiwati',
      'Bhandara','Mauda','Kamptee','Hingna','Katol','Narkhed','Savner',
      'Kalmeshwar','Ramtek','Parshivani','Mowad','Umred','Bhiwapur','Kuhi',
      'Hinganghat','Arvi','Deoli','Seloo','Ashti','Karanja','Samudrapur',
      // Konkan Division
      'Ratnagiri','Sindhudurg','Chiplun','Khed','Dapoli','Mandangad','Lanja',
      'Rajapur','Guhagar','Sangameshwar','Devrukh','Hatkhamba','Palghar',
      'Boisar','Dahanu','Talasari','Vikramgad','Jawhar','Mokhada','Wada',
      'Bhiwandi','Vasai','Virar','Nalasopara','Mira Road','Andheri','Borivali',
      'Kandivali','Malad','Goregaon','Jogeshwari','Bandra','Kurla','Ghatkopar',
      'Mulund','Vikhroli','Chembur','Trombay','Mankhurd','Govandi','Manori',
      'Versova','Juhu','Santacruz','Vile Parle','Andheri East','Powai','Saki Naka',
      'Sakinaka','Chandivali','Asalpha','Ghatkopar East','Vikhroli East',
      'Bhandup','Nahur','Kanjurmarg','Bhandup West','Mulund West',
      'Lonavala','Khandala','Karjat','Khopoli','Neral','Matheran','Pen',
      'Khalapur','Khopoli','Mangaon','Alibag','Thal','Rewas','Belapur',
      'Kharghar','Kamothe','Taloja','Rasayani','Uran','Panvel','Jasai',
      // Additional small towns
      'Ahmednagar','Shrirampur','Kopargaon','Rahata','Rahuri','Newasa','Sangamner',
      'Akole','Parner','Pathardi','Shevgaon','Jamkhed','Karjat Ahmednagar',
      'Shrigonda','Manmad','Nandgaon','Yeola','Sinnar','Niphad','Deola',
      'Kalwan','Satana','Dindori','Trimbakeshwar','Igatpuri','Ghoti','Surgana',
      'Peint','Baglan','Chandwad','Malegaon'
    ]
  },
  {
    state: 'Manipur',
    cities: [
      'Imphal','Thoubal','Bishnupur','Churachandpur','Kakching','Ukhrul','Senapati',
      'Tamenglong','Chandel','Jiribam','Moreh','Lilong','Kangpokpi','Pherzawl',
      'Noney','Tengnoupal','Kamjong','Lamlai','Heingang','Mayang Imphal','Nambol',
      'Moirang','Ningthoukhong','Khongman','Singjamei','Porompat','Kwakeithal',
      'Keisamthong','Yaiskul','Thangmeiband','Keishamthong','Langol','Kangchup',
      'Andro','Sugnu','Wangjing','Khangabok','Yairipok','Kumbi','Ngaikhong',
      'Nambol','Mayang Imphal','Moirang','Ningthoukhong','Torban','Kumbi',
      'Saikul','Sadar Hills','Tadubi','Mao','Maram','Paomata','Kangpokpi',
      'Jiribam','Borobekra','Karong','Nungba','Tamenglong','Tousem','Tamei',
      'Phungyar','Kasom Khullen','Chingai','Kamjong','Jessami','Sangshak',
      'Chassad','Tengnoupal','Moreh','Chakpikarong','Chandel','Machi','Pallel'
    ]
  },
  {
    state: 'Meghalaya',
    cities: [
      'Shillong','Tura','Nongstoin','Jowai','Baghmara','Resubelpara','Mairang',
      'Nongpoh','Williamnagar','Khliehriat','Ampati','Mawkyrwat','Mendipathar',
      'Ranikor','Dawki','Cherrapunji','Sohra','Mawsynram','Mawlai','Lawsohtun',
      'Nongthymmai','Umsning','Byrnihat','Nongkseh','Pynursla','Mawryngkneng',
      'Khatarshnong','Mawthadraishan','Mawkynrew','Sohiong','Smit','Mawlyngot',
      'Shangpung','Amlarem','Laskein','Nartiang','Mynso','Sutnga','Raliang',
      'Rymbai','Khliehriat','Muktapur','Langrin','Nongalbibra','Betasing',
      'Phulbari','Tikrikilla','Rongara','Zikzak','Selsella','Dalu','Bajengdoba',
      'Garobadha','Jengjal','Rongrengre','Tura','Gambegre','Phulbari','Rajabala'
    ]
  },
  {
    state: 'Mizoram',
    cities: [
      'Aizawl','Lunglei','Champhai','Serchhip','Kolasib','Saiha','Lawngtlai',
      'Mamit','Khawzawl','Hnahthial','Saitual','Thenzawl','Biate','Tlabung',
      'Lunglei','Lunglei South','Demagiri','Sangau','Chawngte','Tuipang',
      'Phura','Siaha','Lawngtlai','Koladyne','Tuichawng','Bungtlang','Lungpher',
      'Kolasib','Bilkhawthlir','North Vanlaiphai','Vairengte','Bairabi','Kawlkulh',
      'Tlangnuam','Rangvamual','Tuidam','Chhiahtlang','Darlawn','Phaileng',
      'Kelsih','Sateek','Aibawk','Phullen','Zemabawk','Hunthar','Hlimen',
      'Chhip','Electric Veng','Thuampui','Sialsuk','Reiek','Ngopa','Khawbung',
      'Ngur','Vaphai','Zawlnuam','Tlabung','Tuichang','Zotlang','Leite'
    ]
  },
  {
    state: 'Nagaland',
    cities: [
      'Kohima','Dimapur','Mokokchung','Tuensang','Wokha','Zunheboto','Phek',
      'Mon','Kiphire','Longleng','Peren','Noklak','Chumukedima','Tseminyu',
      'Pfutsero','Meluri','Chozuba','Jakhama','Sechü','Zubza','Jotsoma',
      'Kohima Village','Mezoma','Thizama','Diezephe','Kigwema','Kidima',
      'Khuzama','Dzüleke','Botsa','Zakhama','Kerüma','Mima','Piphema',
      'Tesophenyu','Zubza','Vihokhu','Khonoma','Touphema','Phesama','Chakhabama',
      'Phek','Chozuba','Meluri','Pfutsero','Chiephobozou','Nerhema','Lotha',
      'Wokha','Bhandari','Sanis','Baghty','Doyang','Tizit','Tuli','Longkhim',
      'Noksen','Kiphire','Seyochung','Sangsanyu','Shamator','Noklak','Tobu',
      'Mon','Aboi','Chen','Tizit','Wakching','Mopungchuket','Longsa',
      'Mokokchung','Mangkolemba','Ongpangkong','Lüta','Changtongya','Tuli',
      'Tzudikong','Longchem','Alongkima','Aküluto','Chuchuyimlang','Akuotto',
      'Longshen','Yaongyimti','Tuensang','Noklak','Seyochung','Longkhim',
      'Kiphire','Shamator','Sangsanyu','Chakhabama','Pfutsero','Nerhema'
    ]
  },
  {
    state: 'Odisha',
    cities: [
      'Bhubaneswar','Cuttack','Rourkela','Brahmapur','Sambalpur','Puri','Balasore',
      'Bhadrak','Baripada','Jharsuguda','Bargarh','Rayagada','Angul','Balangir',
      'Dhenkanal','Kendujhar','Koraput','Jeypore','Paradip','Berhampur','Sundargarh',
      'Talcher','Jagatsinghpur','Kendrapara','Jajpur','Nayagarh','Khordha',
      'Nabarangpur','Nuapada','Boudh','Sonepur','Malkangiri','Gajapati','Kandhamal',
      'Mayurbhanj','Deogarh','Ganjam','Phulbani','Baliguda','Udayagiri',
      'Keonjhar','Barbil','Joda','Champua','Badbil','Banspal','Ghasipura',
      'Anandpur','Telkoi','Hatadihi','Patna','Ghatagaon','Jhumpura','Champua',
      'Baripada','Betanati','Jashipur','Karanjia','Kaptipada','Rairangpur',
      'Udala','Bahalda','Bisoi','Bangriposi','Gorumahisani','Baisinga','Bamanghaty',
      'Puri','Nimapara','Kakatpur','Pipili','Delang','Brahmagiri','Konark',
      'Satapada','Krushna Prasad','Gop','Astarang','Kanas','Satyabadi','Sakhigopal',
      'Visakha','Balugaon','Balianta','Tangi','Cuttack','Kendrapara','Aul',
      'Rajnagar','Mahakalpada','Mahakalapara','Pattamundai','Derabish','Garadpur',
      'Marsaghai','Tirtol','Nischintakoili','Salepur','Banki','Tigiria',
      'Athagarh','Narsinghpur','Balikuda','Mahanga','Kanpur','Badamba',
      'Jajpur','Jajpur Road','Binjharpur','Dharmasala','Korei','Sukinda',
      'Rasulpur','Danagadi','Bari','Mangalpur','Bhograi','Baliapal','Remuna',
      'Nilagiri','Jaleswar','Basta','Oupada','Soro','Simulia','Khaira',
      'Tihidi','Chandbali','Dhamnagar','Bhadrak','Basudevpur','Agarpada',
      'Bonth','Angul','Pallahara','Chhendipada','Kaniha','Athamallik','Banarpal',
      'Dhenkanal','Kamakhyanagar','Bhuban','Gondia','Hindol','Parjang','Odapada',
      'Khordha','Begunia','Chilika','Bolagarh','Balipatna','Jatani','Bhubaneswar',
      'Sambalpur','Bamra','Rairakhol','Kuchinda','Jamankira','Naktideul','Dhankauda',
      'Bargarh','Paikmal','Padmapur','Ambabhona','Bijepur','Bhatli','Jharbandh',
      'Balangir','Titilagarh','Patnagarh','Kantabanji','Belpada','Loisingha',
      'Muribahal','Saintala','Agalpur','Deogaon','Khaprakhol','Tureikela',
      'Nuapada','Khariar','Sinapali','Boden','Jonk','Narla','Komna','Bhatli',
      'Sonepur','Birmaharajpur','Binika','Dungripali','Tarbha','Ullunda',
      'Boudh','Harbhanga','Phulbani','Manamunda','Kantamal','Baliguda','Raikia',
      'Gajapati','Paralakhemundi','Mohana','Kashinagar','Rayagada','Kasipur',
      'Padmapur','Gudari','Muniguda','Bissamcuttack','Chandahandi','Gunupur',
      'Koraput','Jeypore','Nabarangpur','Umerkote','Dabugam','Kosagumuda',
      'Malkangiri','Kalimela','Mathili','Korkunda','Padia','Chitrakonda',
      'Ganjam','Chikiti','Polasara','Surada','Bhanjanagar','Sorada','Sanakhemundi',
      'Buguda','Khallikote','Purushottampur','Digapahandi','Chatrapur','Berhampur'
    ]
  },
  {
    state: 'Punjab',
    cities: [
      'Ludhiana','Amritsar','Jalandhar','Patiala','Bathinda','Mohali','Hoshiarpur',
      'Gurdaspur','Pathankot','Moga','Firozpur','Abohar','Malerkotla','Khanna',
      'Muktsar','Phagwara','Kapurthala','Fatehgarh Sahib','Sangrur','Barnala',
      'Rajpura','Batala','Zirakpur','Kharar','Faridkot','Rupnagar','Nawanshahr',
      'Tarn Taran','Mansa','Nabha','Sunam','Dhuri','Samana','Jagraon','Raikot',
      'Khamano','Banga','Dasuya','Garhshankar','Mukerian','Talwara','Nangal',
      'Anandpur Sahib','Morinda','Ropar','Chamkaur Sahib','Fatehgarh Sahib',
      'Sirhind','Patiala','Rajpura','Nabha','Sangrur','Dhuri','Malerkotla',
      'Ahmedgarh','Lehra Gaga','Longowal','Moonak','Sunam','Bhawanigarh',
      'Dirba','Sherpur','Lehragaga','Barnala','Tapa','Bhadaur','Mehla Kalan',
      'Fatehgarh Churian','Dera Baba Nanak','Gurdaspur','Dhariwal','Sri Hargobindpur',
      'Batala','Qadian','Narot Mehra','Kartarpur','Nakodar','Shahkot','Phillaur',
      'Goraya','Nurmahal','Adampur','Phagwara','Kapurthala','Sultanpur Lodhi',
      'Jalandhar','Khambra','Lohian Khas','Maqsudan','Bhogpur','Dakaur',
      'Hoshiarpur','Una','Garhshankar','Dasuya','Mukerain','Mehatpur',
      'Tanda Urmur','Talwara','Hajipur','Bohni','Bassi Pathana','Morinda',
      'Chamkaur Sahib','Ropar','Kharar','Naya Nangal','Bela','Anandpur',
      'Fatehgarh Sahib','Amloh','Patran','Dera Bassi','Banur','Lalru',
      'Manimajra','Khanna','Samrala','Machiwara','Pakhowal','Rahon','Balachaur',
      'Nawanshahr','Banga','Nangal Ambyan','Gidderbaha','Malout','Lambi',
      'Muktsar','Kot Bhai','Faridkot','Jaitu','Kotakpura','Baghapurana',
      'Zira','Firozpur','Mamdot','Makhu','Guru Har Sahai','Talwandi Bhai',
      'Abohar','Fazilka','Jalalabad','Arniwala','Bathinda','Rampura Phul',
      'Nathana','Talwandi Sabo','Mansa','Budhlada','Sardulgarh','Budhladha',
      'Bhikhiwind','Valtoha','Patti','Khem Karan','Tarn Taran','Harike'
    ]
  },
  {
    state: 'Rajasthan',
    cities: [
      'Jaipur','Jodhpur','Kota','Bikaner','Ajmer','Udaipur','Bhilwara','Alwar',
      'Bharatpur','Sikar','Pali','Sri Ganganagar','Kishangarh','Baran','Dhaulpur',
      'Tonk','Beawar','Hanumangarh','Gangapur City','Sawai Madhopur','Churu',
      'Jhunjhunu','Nagaur','Banswara','Dungarpur','Chittorgarh','Jaisalmer',
      'Barmer','Jalore','Sirohi','Rajsamand','Bundi','Karauli','Pratapgarh',
      'Jhalawar','Bhinmal','Falna','Sumerpur','Sojat','Pilani','Nawalgarh',
      'Ramganj Mandi','Phalodi','Pokaran','Deshnok','Sujangarh','Ladnu','Ratangarh',
      'Sardarshahar','Suratgarh','Anupgarh','Khetri','Neem Ka Thana','Fatehpur',
      'Nokha','Phulera','Sambhar','Jobner','Chaksu','Malpura','Uniyara','Toda',
      'Dausa','Bandikui','Lalsot','Geejgarh','Mahuwa','Sikandara','Nangal',
      'Lalsot','Gangapur','Hindaun','Sapotara','Karauli','Nadoti','Todabhim',
      'Mandrayal','Bayana','Rupbas','Dig','Nadbai','Kumher','Deeg','Nagar',
      'Weir','Kaman','Bhusawar','Halena','Sever','Rundi','Bahror','Tijara',
      'Kishangarh Renwal','Shajahanpur','Kotputli','Bansur','Thanagazi',
      'Rajgarh','Alwar','Ramgarh','Kathumar','Laxmangarh','Kishangarhbas',
      'Mundawar','Tapukara','Bhiwadi','Bawal','Neemrana','Narainpur','Mewat',
      'Mandawa','Mukundgarh','Jhunjhunu','Chirawa','Udaipurwati','Khetri',
      'Singhana','Khandela','Neem Ka Thana','Srimadhopur','Reengus','Sikar',
      'Fatehpur','Lachhmangarh','Ramgarh Shekhawati','Danta Ramgarh','Shyampur',
      'Nagaur','Merta','Ladnun','Didwana','Jayal','Parbatsar','Kuchaman',
      'Nawa','Makrana','Mundwa','Degana','Riyan Badi','Khinvsar','Deh',
      'Bikaner','Deshnok','Nokha','Kolayat','Bajju','Khajuwala','Sujangarh',
      'Sardarshahar','Rajaldesar','Dungargarh','Ratangarh','Taranagar','Bidasar',
      'Churu','Salasar','Ratangarh','Rajgarh','Sujangarh','Bidasar','Taranagar',
      'Sri Ganganagar','Suratgarh','Padampur','Raisinghnagar','Anupgarh','Gharsana',
      'Hanumangarh','Tibi','Sangaria','Pilibanga','Rawatsar','Bhadra','Nohar',
      'Jodhpur','Phalodi','Bilara','Osian','Bhopalgarh','Shergarh','Pipar',
      'Lohawat','Balesar','Mandore','Khichan','Dechhu','Tivri','Tinwari',
      'Barmer','Balotra','Pachpadra','Siwana','Gudamalani','Dhorimanna',
      'Chohtan','Ramsar','Baitu','Sindhari','Sheo','Baytu','Girirani',
      'Jaisalmer','Sam','Pokaran','Fatehgarh','Ramgarh','Nachna',
      'Jalore','Bhinmal','Sanchore','Ahore','Raniwara','Sayla','Jaswantpura',
      'Sirohi','Abu Road','Mount Abu','Sheoganj','Reodar','Pindwara','Taleti',
      'Udaipur','Nathdwara','Rajsamand','Bhim','Kumbhalgarh','Amet','Devgarh',
      'Chittorgarh','Begun','Bari Sadri','Nimbahera','Kapasan','Rawatbhata',
      'Dungarpur','Sagwara','Aspur','Simalwara','Bichhiwara','Sabla','Chorasi',
      'Banswara','Kushalgadh','Bagidora','Ghatol','Garhi','Arthuna','Gangapur',
      'Pratapgarh','Arnod','Dhariawad','Peepal Khunt','Chhoti Sadri'
    ]
  },
  {
    state: 'Sikkim',
    cities: [
      'Gangtok','Namchi','Mangan','Gyalshing','Rangpo','Jorethang','Nayabazar',
      'Singtam','Pakyong','Soreng','Ravangla','Yuksom','Pelling','Geyzing',
      'Legship','Dentam','Uttarey','Rinchenpong','Kaluk','Barmiok','Tashiding',
      'Lachen','Lachung','Chungthang','Dzongu','Mangan','Kabi','Phodong',
      'Rumtek','Martam','Ranka','Ralang','Temi','Damthang','Yangang','Sorthang',
      'Majitar','Rhenock','Rongli','Aritar','Padamchen','Chujachen','Gnathang',
      'Rorathang','Lingtam','Melli','Namthang','Turuk','Serwa','Nagri',
      'Mellidara','Bermiok','Hee Bermiok','Mangalbaria','Daramdin','Zoom',
      'Naya Bazar','Buriakhop','Chereching','Tikpur','Singmo'
    ]
  },
  {
    state: 'Tamil Nadu',
    cities: [
      'Chennai','Coimbatore','Madurai','Tiruchirappalli','Salem','Tirunelveli',
      'Tiruppur','Vellore','Erode','Thoothukkudi','Dindigul','Thanjavur',
      'Ranipet','Sivakasi','Karur','Udhagamandalam','Hosur','Nagercoil',
      'Kanchipuram','Kumarapalayam','Karaikkudi','Pudukkottai','Pollachi',
      'Rajapalayam','Pattukkottai','Gudiyatham','Tiruvannamalai','Vaniyambadi',
      'Ambur','Theni','Krishnagiri','Namakkal','Cuddalore','Villupuram',
      'Tindivanam','Chengalpattu','Tiruvallur','Nagapattinam','Mayiladuthurai',
      'Kumbakonam','Tiruvarur','Ramanathapuram','Sivaganga','Virudhunagar',
      'Tenkasi','Tirupathur','Perambalur','Ariyalur','Dharmapuri','Kallakurichi',
      'Tirupattur','Ranipet','Nilgiris','Ooty','Coonoor','Kotagiri','Gudalur',
      'Mettupalayam','Pollachi','Palladam','Avinashi','Tirupur','Udumalpet',
      'Dharapuram','Kangeyam','Vellakoil','Bhavani','Perundurai','Anthiyur',
      'Gobichettipalayam','Sathyamangalam','Bhavanisagar','Kolathur','Rasipuram',
      'Tiruchengode','Paramathi','Vennandur','Kumarapalayam','Jalakandapuram',
      'Omalur','Mettur','Yercaud','Attur','Sankari','Salem','Vazhapadi',
      'Idappadi','Edappadi','Thalaivasal','Gangavalli','Pethanaickenpalayam',
      'Panamarathupatti','Seerankuppam','Kunnathur','Tirukoilur','Sankarapuram',
      'Ulundurpet','Kallakurichi','Chinnasalem','Rishivandiyam','Kalvarayan Hills',
      'Villupuram','Gingee','Mailam','Thirukoilure','Kandamangalam','Vikravandi',
      'Cuddalore','Panruti','Chidambaram','Kattumannarkoil','Kurinjipadi',
      'Bhuvanagiri','Vriddhachalam','Neyveli','Srimushnam','Annamalai Nagar',
      'Coromandel','Parangipettai','Pichavaram','Sirkazhi','Vaitheeswaran Koil',
      'Sirkazhi','Nagapattinam','Velankanni','Vedaranyam','Thiruthuraipoondi',
      'Papanasam','Thanjavur','Kumbakonam','Papanasam','Pattukottai','Budalur',
      'Tiruvaiyaru','Needamangalam','Peravurani','Orathanadu','Thiruvidaimaruthur',
      'Tiruvarur','Kodavasal','Mannargudi','Nannilam','Valangaiman','Muthupet',
      'Ramanathapuram','Paramakudi','Mudukulathur','Kadaladi','Rameswaram',
      'Mandapam','Thondi','Thiruvadanai','Kamuthi','Tiruvadanai','Keelakarai',
      'Ervadi','Kilakkarai','Uchipuli','Devipattinam','Sayalkudi','Rajasingamangalam',
      'Sivaganga','Devakottai','Karaikudi','Manamadurai','Singampunari','Thiruppuvanam',
      'Kalayarkovil','Tiruppattur','Ilayangudi','Virudhunagar','Sattur','Sivakasi',
      'Vembakottai','Aruppukkottai','Srivilliputtur','Rajapalayam','Watrap',
      'Tiruchuli','Kariapatti','Tiruvil','Narikudi','Tiruvil','Nerkuppai',
      'Tenkasi','Kadayam','Alangulam','Sivagiri','Sankarankovil','Ayikudi',
      'Panagudi','Melaneelithanallur','Kadayanallur','Tirunelveli','Palayamkottai',
      'Nanguneri','Cheranmahadevi','Valliyur','Radhapuram','Ambasamudram',
      'Kalakkad','Manimuthar','Papanasam','Manapad','Tiruchendur','Kayalpattinam',
      'Srivaikundam','Ottapidaram','Kovilpatti','Vilathikulam','Udangudi',
      'Nagercoil','Marthandam','Kuzhithurai','Killiyoor','Padmanabhapuram',
      'Thuckalay','Colachel','Munchirai','Eraniel','Agastheeswaram','Suchindram',
      'Thiruvattar','Nithravilai','Rajakkamangalam','Thicksy','Kanyakumari',
      'Thendral Nagar','Maraimalai Nagar','Vandalur','Paranur','Singaperumal Koil',
      'Chembarambakkam','Tiruvallur','Avadi','Ambattur','Ennore','Manali',
      'Redhills','Ponneri','Gummidipoondi','Tiruttani','Arakkonam','Sholinghur',
      'Kaveripakkam','Walajah','Arcot','Ranipet','Vellore','Katpadi','Ambur',
      'Vaniyambadi','Gudiyatham','Tirupattur','Jolarpet','Krishnagiri','Denkanikotta',
      'Hosur','Kelamangalam','Uthangarai','Bargur','Veppanahalli','Rayakottai',
      'Dharmapuri','Harur','Palacode','Pennagaram','Pappireddipatti','Nallampalli',
      'Chetpet','Morappur','Tiruvannamalai','Polur','Cheyyar','Vandavasi',
      'Arani','Arcot','Kilpennathur','Chengam','Thandrampet','Thellar',
      'Maduranthakam','Uthiramerur','Kanchipuram','Sriperumbudur','Acharapakkam',
      'Tambaram','Pallavaram','Chromepet','Selaiyur','Chitlapakkam'
    ]
  },
  {
    state: 'Telangana',
    cities: [
      'Hyderabad','Warangal','Nizamabad','Karimnagar','Khammam','Ramagundam',
      'Mahbubnagar','Nalgonda','Adilabad','Suryapet','Miryalaguda','Jagtial',
      'Mancherial','Bhongir','Medak','Siddipet','Bodhan','Koratla','Banswada',
      'Sangareddy','Vikarabad','Sircilla','Kamareddy','Wanaparthy','Nagarkurnool',
      'Gadwal','Jogulamba','Yadadri','Bhuvanagiri','Kothagudem','Mahabubabad',
      'Jangaon','Peddapalli','Jayashankar','Asifabad','Komaram Bheem','Nirmal',
      'Narayanpet','Mulugu','Narayanpet','Wanaparthy','Gadwal','Nagarkurnool',
      'Manthani','Dornakal','Yellandu','Wyra','Madhira','Palvancha','Kothagudem',
      'Bhadrachalam','Burgampahad','Dammapeta','Aswaraopeta','Mulakanupur',
      'Mahabubabad','Narsampet','Warangal','Hanamkonda','Kazipet','Parkal',
      'Bhupalpally','Mulugu','Eturunagaram','Yellandu','Mahadevpur','Thorrur',
      'Jangaon','Ghanpur','Devaruppula','Palakurthi','Kodad','Nakrekal',
      'Huzurnagar','Mellachervu','Mattam','Narayanpet','Moinabad','Chevella',
      'Vikarabad','Tandur','Parigi','Kulcharam','Kotepalli','Sangareddy',
      'Narayankhed','Andole','Zahirabad','Jogipet','Nyalkal','Pulkal',
      'Toopran','Ramayampet','Medak','Papannapet','Narsapur','Patancheru',
      'Siddipet','Dubbaka','Gajwel','Kowdipally','Doultabad','Cheriyal',
      'Husnabad','Sircilla','Vemulawada','Karimnagar','Huzurabad','Jagtial',
      'Dharmapuri','Raikal','Gollapalli','Metpally','Koratla','Banswada',
      'Kamareddy','Yellareddy','Lingampet','Bichkunda','Bhiknoor','Domakonda',
      'Bodhan','Armur','Nizamabad','Varni','Balkonda','Madnur','Pitlam',
      'Peddapalli','Ramagundam','Manthani','Sultanabad','Godavarikhani',
      'Jammikunta','Karimnagar','Huzurabad','Veenavanka','Choppadandi',
      'Jagitial','Koratla','Renjal','Mallial','Dharmapuri','Kodimial',
      'Mancherial','Bellampalli','Chennur','Luxettipet','Bhainsa','Nirmal',
      'Mudhole','Dilawarpur','Khanapur','Kubeer','Bazarhathnoor','Adilabad',
      'Utnoor','Asifabad','Sirpur','Wankdi','Dahegaon','Tiryani','Jainoor',
      'Hyderabad','Secunderabad','Cyberabad','LB Nagar','Uppal','Malkajgiri',
      'Alwal','Begumpet','Ameerpet','Banjara Hills','Jubilee Hills','Madhapur',
      'Gachibowli','Kondapur','Kukatpally','Miyapur','Patancheru','Medchal',
      'Shamshabad','Rajendranagar','Mehdipatnam','Tolichowki','Attapur',
      'Saroornagar','Dilsukhnagar','Hayathnagar','Ibrahimpatnam','Ghatkesar'
    ]
  },
  {
    state: 'Tripura',
    cities: [
      'Agartala','Dharmanagar','Udaipur','Kailasahar','Belonia','Khowai','Ambassa',
      'Bishalgarh','Sonamura','Melaghar','Teliamura','Sabroom','Kamalpur','Kumarghat',
      'Amarpur','Jirania','Mohanpur','Majlishpur','Ranir Bazar','Jogendranagar',
      'Barjala','Dukli','Mandai','Boxanagar','Ranirbazar','Anandanagar','Bodhjungnagar',
      'Bamutia','Charilam','Matabari','Rajnagar','Rupaichari','Karbook','Bagma',
      'Nalchar','Satchand','Twistar','Chawmanu','Reang','Longtarai Valley',
      'North Tripura','Panisagar','Dasda','Laljuri','Kadamtala','Pecharthal',
      'Kanchanpur','Betcherra','Kumarghat','Machmara','Churaibari','Santirbazar',
      'Hrishyamukh','Jolaibari','Manu','Damcherra','Jiraniya','Tulashikhar'
    ]
  },
  {
    state: 'Uttar Pradesh',
    cities: [
      'Lucknow','Kanpur','Ghaziabad','Agra','Meerut','Varanasi','Prayagraj',
      'Bareilly','Aligarh','Moradabad','Saharanpur','Gorakhpur','Noida',
      'Firozabad','Jhansi','Muzaffarnagar','Mathura','Budaun','Rampur',
      'Shahjahanpur','Farrukhabad','Mau','Hapur','Etawah','Mirzapur',
      'Bulandshahr','Sambhal','Amroha','Hardoi','Fatehpur','Raebareli',
      'Orai','Sitapur','Bahraich','Modinagar','Unnao','Jaunpur','Lakhimpur',
      'Hathras','Banda','Pilibhit','Barabanki','Khurja','Gonda','Sultanpur',
      'Azamgarh','Bijnor','Sahaswan','Basti','Chandausi','Akbarpur','Ballia',
      'Tanda','Greater Noida','Deoria','Faizabad','Ayodhya','Mainpuri',
      'Lalitpur','Etah','Kasganj','Hamirpur','Mahoba','Chitrakoot','Auraiya',
      'Kannauj','Kanpur Dehat','Pratapgarh','Kaushambi','Amethi','Sant Kabir Nagar',
      'Siddharthnagar','Maharajganj','Kushinagar','Balrampur','Shrawasti',
      'Bagpat','Shamli','Bhadohi','Chandauli','Ghazipur','Sonbhadra',
      'Jalaun','Kheri','Rae Bareli','Shravasti','Ambedkar Nagar','Amroha',
      'Amethi','Auraiya','Ayodhya','Azamgarh','Baghpat','Bahraich','Ballia',
      'Banda','Barabanki','Bareilly','Basti','Bijnor','Budaun','Bulandshahr',
      'Chandauli','Chitrakoot','Deoria','Etah','Etawah','Faizabad','Farrukhabad',
      'Fatehpur','Firozabad','Gautam Buddha Nagar','Ghaziabad','Ghazipur',
      'Gonda','Gorakhpur','Hamirpur','Hapur','Hardoi','Hathras','Jalaun',
      'Jaunpur','Jhansi','Kannauj','Kanpur Dehat','Kanpur Nagar','Kasganj',
      'Kaushambi','Kushinagar','Lakhimpur','Lalitpur','Lucknow','Mahoba',
      'Maharajganj','Mainpuri','Mathura','Mau','Meerut','Mirzapur',
      'Moradabad','Muzaffarnagar','Pilibhit','Pratapgarh','Prayagraj',
      'Raebareli','Rampur','Saharanpur','Sambhal','Sant Kabir Nagar',
      'Shahjahanpur','Shamli','Shravasti','Siddharthnagar','Sitapur',
      'Sonbhadra','Sultanpur','Unnao','Varanasi','Kheri','Lakhimpur Kheri',
      'Muzaffarnagar','Saharanpur','Bijnor','Amroha','Moradabad','Rampur',
      'Bareilly','Pilibhit','Shahjahanpur','Budaun','Hardoi','Sitapur',
      'Hathras','Aligarh','Mathura','Etah','Mainpuri','Firozabad',
      'Agra','Etawah','Auraiya','Kannauj','Fatehpur','Kanpur','Unnao',
      'Lucknow','Raebareli','Amethi','Sultanpur','Barabanki','Faizabad',
      'Ambedkar Nagar','Bahraich','Shrawasti','Balrampur','Gonda','Basti',
      'Sant Kabir Nagar','Siddharthnagar','Gorakhpur','Maharajganj',
      'Deoria','Kushinagar','Kushi Nagar','Mau','Azamgarh','Ballia',
      'Jaunpur','Ghazipur','Varanasi','Chandauli','Mirzapur','Sonbhadra',
      'Allahabad','Kaushambi','Chitrakoot','Banda','Hamirpur','Mahoba',
      'Jhansi','Lalitpur','Jalaun','Orai','Kanpur Dehat','Farrukhabad',
      'Rampur','Sahaswan','Nawabganj','Dhampur','Najibabad','Bijnor',
      'Shamli','Kairana','Muzaffarnagar','Bulandshahr','Khurja','Hapur',
      'Ghaziabad','Noida','Dadri','Sikandrabad','Pahasu','Dibai',
      'Meerut','Baghpat','Sardhana','Garhmukteshwar','Hapur',
      'Pilkhuwa','Loni','Dasna','Modinagar','Muradnagar','Tronica City',
      'Ghaziabad','Crossings Republik','Raj Nagar Extension',
      'Allahabad','Naini','Phaphamau','Jhunsi','Srinath','Karari',
      'Sirathu','Karchana','Meja','Shankargarh','Handia','Chail',
      'Koraon','Kori','Saidabad','Bara','Phulpur','Soraon','Bari',
      'Varanasi','Ramnagar','Sarnath','Mughal Sarai','Chandauli',
      'Gyanpur','Bhadohi','Gopiganj','Aurai','Suriyawan','Chakia',
      'Mirzapur','Chunar','Marihan','Majhawan','Lalganj','Hallia',
      'Obra','Renukoot','Shaktinagar','Pipri','Robertsganj','Dudhi',
      'Nakaha','Singrauli','Gorakhpur','Deoria','Padrauna','Kasia',
      'Hata','Gauri Bazar','Bhatpar Rani','Rudrapur','Salempur',
      'Barhaj','Lar','Bansi','Basti','Khalilabad','Menhdawal',
      'Maharajganj','Naugarh','Pharenda','Anand Nagar','Siswa Bazar',
      'Kushinagar','Khadda','Tamkuhi Road','Padrauna','Hata',
      'Balrampur','Tulsipur','Utraula','Gainsari','Shrawasti',
      'Bhinga','Ikauna','Gond','Bahraich','Nanpara','Kaisarganj',
      'Payagpur','Jaleswarnath','Balha','Rupaidiha','Motipur'
    ]
  },
  {
    state: 'Uttarakhand',
    cities: [
      'Dehradun','Haridwar','Roorkee','Haldwani','Rudrapur','Kashipur','Rishikesh',
      'Kotdwar','Ramnagar','Pithoragarh','Jaspur','Manglaur','Vikasnagar',
      'Sitarganj','Tehri','Almora','Nainital','Mussoorie','Pauri','Srinagar',
      'Chamoli','Gopeshwar','Rudraprayag','Bageshwar','Champawat','Lansdowne',
      'Mukteshwar','Ranikhet','Dwarahat','Bazpur','Khatima','Gadarpur',
      'Kichha','Sultanpur','Tanakpur','Lohaghat','Champawat','Purnagiri',
      'Bageshwar','Kapkot','Garud','Didihat','Gangolihat','Berinag','Munsyari',
      'Dhararchula','Dharchula','Jauljibi','Thal','Askot','Pithoragarh',
      'Almora','Ranikhet','Dwarahat','Salthi','Chaukhutia','Someshwar',
      'Tarikhet','Bhikiyasain','Devalgarh','Syalde','Chitai','Jainti',
      'Nainital','Bhimtal','Sattal','Bhowali','Ramgarh','Ramnagar','Corbett',
      'Haldwani','Lalkuan','Kathgodam','Bajpur','Rudrapur','Gadarpur',
      'Sitarganj','Khatima','Pilibhit','Tanakpur','Champawat','Banbasa',
      'Haridwar','Roorkee','Laksar','Manglaur','Jwalapur','Bhel','Shyampur',
      'Dehradun','Rishikesh','Doiwala','Vikasnagar','Selaqui','Herbertpur',
      'Sahiya','Chakrata','Tyuni','Purola','Barkot','Mori','Naugaon',
      'Uttarkashi','Bhatwari','Gangnani','Harsil','Sangla','Sukki','Lanka',
      'Chamba','Deoprayag','Kirtinagar','Devprayag','Srinagar Garhwal',
      'Pauri','Kotdwar','Satpuli','Naini Bazar','Dugadda','Ekeshwar',
      'Chamoli','Gopeshwar','Joshimath','Badrinath','Hemkund','Tharali',
      'Karnaprayag','Gairsain','Nauti','Nandprayag','Ghitura','Maikhanda',
      'Rudraprayag','Kedarnath','Agastyamuni','Ukhimath','Tilwara','Guptkashi',
      'Tehri','Chinyalisaur','Ghansali','Kirti Nagar','Narendranagar',
      'New Tehri','Lambgaon','Pratapnagar','Jakhnidhar','Maletha'
    ]
  },
  {
    state: 'West Bengal',
    cities: [
      'Kolkata','Asansol','Siliguri','Durgapur','Bardhaman','Malda','Baharampur',
      'Habra','Kharagpur','Shantipur','Dankuni','Dhulian','Ranaghat','Haldia',
      'Raiganj','Krishnanagar','Nabadwip','Medinipur','Jalpaiguri','Balurghat',
      'Basirhat','Bankura','Chakdah','Darjeeling','Alipurduar','Purulia',
      'Bishnupur','Cooch Behar','Tamluk','Contai','Diamond Harbour','Barrackpore',
      'Barasat','Berhampore','Bolpur','Suri','Burdwan','Howrah','Hooghly',
      'Serampore','Chandannagar','Uttarpara','Rishra','Konnagar','Bansberia',
      'Bandel','Arambagh','Khanakul','Goghat','Pursurah','Tarakeswar',
      'Pandua','Haripal','Dhaniakhali','Champdani','Baidyabati','Kamarhatty',
      'Titagarh','Naihati','Bhatpara','Panihati','Sodpur','Khardah','Kamarhati',
      'North Barrackpur','Barrackpur','Noapara','New Barrackpur','Garulia',
      'Halisahar','Shyamnagar','Belgharia','Baranagar','Dum Dum','Rajarhat',
      'New Town','Salt Lake','Lake Town','Dum Dum Cantonment','Sodepur',
      'Madhyamgram','Ashokenagar','Gobardanga','Duttapukur','Deganga',
      'Bangaon','Bongaon','Gaighata','Baduria','Swarupnagar','Minakhan',
      'Basirhat','Taki','Sandeshkhali','Hingalganj','Hasnabad','Hashnabd',
      'Uluberia','Bagnan','Amta','Udaynarayanpur','Jagatballavpur','Domjur',
      'Panchla','Shyampur','Bally','Belur','Liluah','Santragachi',
      'Shibpur','Garden Reach','Metiabruz','Maheshtala','Budge Budge',
      'Narendrapur','Rajpur','Sonarpur','Baruipur','Magrahat','Bishnupur',
      'Diamond Harbour','Falta','Kulpi','Mandirbazar','Canning','Basanti',
      'Gosaba','Sandeshkhali','Hingalganj','Nimtouri','Sandeshkhali',
      'Tamluk','Haldia','Mecheda','Kolaghat','Mahishadal','Sutahata',
      'Panskura','Kharagpur','Midnapore','Keshpur','Chandrakona','Ghatal',
      'Debra','Daspur','Moyna','Contai','Ramnagar','Bhagwanpur','Nandigram',
      'Tamluk','Egra','Khejuri','Patashpur','Nandakumar','Sutahata',
      'Balarampur','Purulia','Raghunathpur','Santuri','Jhalda','Puncha',
      'Manbazar','Barabazar','Bandwan','Hura','Kashipur','Para',
      'Bishnupur','Bankura','Khatra','Raipur','Onda','Saltora','Chhatna',
      'Sonamukhi','Indpur','Taldangra','Gangajalghati','Barjora','Mejia',
      'Burdwan','Kalna','Katwa','Memari','Bhatar','Ausgram','Galsi',
      'Jamalpur','Monteswar','Khandaghosh','Bhatar','Raina','Mangolkot',
      'Bolpur','Sriniketan','Illambazar','Rajnagar','Nanoor','Rampurhat',
      'Murarai','Nalhati','Mayureswar','Sainthia','Dubrajpur','Suri',
      'Khoyrasol','Siuri','Labhpur','Mohammad Bazar','Ararambag','Howrah',
      'Balagarh','Pandua','Polba','Dhaniakhali','Berhampur','Lalgola',
      'Raninagar','Farakka','Suti','Sagardighi','Jangipur','Bharatpur',
      'Kandi','Khargram','Beldanga','Nabagram','Baharampur','Murshidabad',
      'Jiaganj','Azimganj','Jalangi','Domkal','Raghunathganj','Katlamari',
      'Malda','Harishchandrapur','Chanchal','Ratua','Kaliachak','Manikchak',
      'Gazole','Bamangola','Habibpur','Gajol','Englishbazar','Old Malda',
      'Dalkhola','Islampur','Kaliyaganj','Raiganj','Itahar','Hemtabad',
      'Karandighi','Goalpokhar','Chopra','Islampur','Darjeeling','Siliguri',
      'Kurseong','Mirik','Kalimpong','Jalpaiguri','Maynaguri','Dhupguri',
      'Mal','Nagrakata','Matiali','Kranti','Berubari','Kumargram',
      'Alipurduar','Falakata','Cooch Behar','Mathabhanga','Tufanganj',
      'Mekhliganj','Sitai','Haldibari','Dinhata','Sitalkuchi','Baxirhat',
      'Balurghat','Gangarampur','Kushmandi','Hili','Tapan','Kumbhiram',
      'Sarat','Patiram','Malda','Dalkhola','Raiganj','Islampur'
    ]
  },
  // Union Territories
  {
    state: 'Delhi',
    cities: [
      'New Delhi','Connaught Place','Chandni Chowk','Karol Bagh','Paharganj',
      'Lajpat Nagar','Greater Kailash','Saket','Malviya Nagar','Hauz Khas',
      'Green Park','Safdarjung','RK Puram','Munirka','Vasant Vihar',
      'Vasant Kunj','Mehrauli','Chhatarpur','Chhattarpur','Sultanpur',
      'Bijwasan','Dwarka','Uttam Nagar','Janakpuri','Vikaspuri','Tilak Nagar',
      'Subhash Nagar','Tagore Garden','Rajouri Garden','Kirti Nagar',
      'Moti Nagar','Punjabi Bagh','Paschim Vihar','Shalimar Bagh',
      'Ashok Vihar','Pitampura','Model Town','Rohini','Rithala','Bawana',
      'Narela','Alipur','Bakhtawarpur','Burari','Mukherjee Nagar',
      'Civil Lines','Kashmere Gate','Shastri Nagar','Rani Bagh','Saraswati Vihar',
      'Shakurpur','Khyala','Madipur','Ramesh Nagar','Inderpuri','Patel Nagar',
      'Rajinder Nagar','Mayapuri','Hari Nagar','Dabri','Kakrola','Uttam Nagar',
      'Bindapur','Nawada','Hastsal','Nihal Vihar','Mohan Garden','Palam',
      'Delhi Cantonment','Sadar Bazar','Najafgarh','Dhansa','Dichaon',
      'Chhawla','Roshanpura','Kair','Jaffarpur','Mitraon','Nasirpur',
      'Shahdara','Preet Vihar','Karkardooma','Anand Vihar','Patparganj',
      'Mayur Vihar','Kondli','Samaspur','Gazipur','Mandawali','Vishwas Nagar',
      'Vivek Vihar','Dilshad Garden','Loni Border','Harsh Vihar',
      'Seelampur','Welcome','Jagat Puri','Shastri Park','Geeta Colony',
      'Gandhi Nagar','Krishna Nagar','Ram Nagar','Laxmi Nagar','Nirman Vihar',
      'East Vinod Nagar','IP Extension','Trilokpuri','Kalyanpuri','Khichripur',
      'Garhi','Sarai Kale Khan','New Friends Colony','Jasola','Okhla',
      'Govindpuri','Kalkaji','Tughlakabad','Badarpur','Sangam Vihar',
      'Sarita Vihar','Jamia Nagar','Abul Fazal Enclave','Shaheen Bagh',
      'Batla House','Noor Nagar','Harkesh Nagar','Madanpur Khadar',
      'Jaitpur','Tekhand','Pul Pehlad','Deoli','Tigri','Sangam Vihar',
      'Naraina','Moti Bagh','Nangloi','Mundka','Nilothi','Ghevra',
      'Tikri','Baprola','Mundka Industrial','Punjabi Bagh West'
    ]
  },
  {
    state: 'Jammu & Kashmir',
    cities: [
      'Srinagar','Jammu','Anantnag','Baramulla','Sopore','Udhampur','Kathua',
      'Poonch','Rajouri','Punch','Bandipore','Ganderbal','Kupwara','Shopian',
      'Pulwama','Kulgam','Budgam','Doda','Kishtwar','Ramban','Reasi','Samba',
      'Akhnoor','Nagrota','Sidhra','Bishnah','Hiranagar','Samba','Vijaypur',
      'Banihal','Ramban','Batote','Kud','Patnitop','Doda','Bhaderwah',
      'Kishtwar','Inderwal','Padder','Marwah','Chatroo','Dachan','Warwan',
      'Poonch','Mendhar','Mandi','Surankote','Mankote','Loran','Haveli',
      'Rajouri','Kalakote','Nowshera','Darhal','Thanna Mandi','Budhal',
      'Mahore','Chassana','Reasi','Katra','Mahore','Pouni','Arnas',
      'Udhampur','Chenani','Majalta','Ramnagar','Tikri','Lander','Panchari',
      'Basohli','Billawar','Bani','Samba','Vijaypur','Ramkote','Purmandal',
      'Barnoti','Ghagwal','Jogwan','Nagrota Gujroo','Kathua','Hiranagar',
      'Qazigund','Bijbehara','Dooru','Pahalgam','Kokernag','Dacchan',
      'Bandipora','Sumbal','Hajin','Gurez','Tulail','Shadipora','Sopore',
      'Kupwara','Lolab','Keran','Handwara','Kralpora','Tekipora','Magam',
      'Baramulla','Pattan','Tangmarg','Gulmarg','Rafiabad','Uri','Rampur',
      'Srinagar','Budgam','Chadoora','Beerwah','Charar-e-Sharief','Narbal',
      'Pulwama','Pampore','Tral','Awantipora','Kakapora','Rajpora','Shopian',
      'Kulgam','Damhal Hanji Pora','Yaripora','Devsar','Frisal','Qaimoh'
    ]
  },
  {
    state: 'Ladakh',
    cities: [
      'Leh','Kargil','Nubra','Zanskar','Drass','Diskit','Khalsi','Padum',
      'Saspol','Nimoo','Basgo','Alchi','Phyang','Spituk','Shey','Thiksey',
      'Hemis','Matho','Stok','Choglamsar','Saboo','Sankar','Changspa',
      'Leh Market','Kargil','Sankoo','Suru','Shargole','Batalik','Hardas',
      'Panikhar','Rangdum','Padum','Zangla','Stod','Lungnak','Zanskar',
      'Hunder','Turtuk','Thoise','Sumur','Panamik','Warshi','Bogdang',
      'Tirith','Siachen','Tangtse','Durbuk','Chumathang','Nyoma','Mahe',
      'Hanle','Demchok','Tso Moriri','Tsaga','Chushul','Rezang La'
    ]
  },
  {
    state: 'Chandigarh',
    cities: [
      'Chandigarh','Sector 1','Sector 2','Sector 3','Sector 4','Sector 5',
      'Sector 6','Sector 7','Sector 8','Sector 9','Sector 10','Sector 11',
      'Sector 12','Sector 14','Sector 15','Sector 16','Sector 17','Sector 18',
      'Sector 19','Sector 20','Sector 21','Sector 22','Sector 23','Sector 24',
      'Sector 25','Sector 26','Sector 27','Sector 28','Sector 29','Sector 30',
      'Sector 31','Sector 32','Sector 33','Sector 34','Sector 35','Sector 36',
      'Sector 37','Sector 38','Sector 39','Sector 40','Sector 41','Sector 42',
      'Sector 43','Sector 44','Sector 45','Sector 46','Sector 47','Sector 48',
      'Sector 49','Sector 50','Sector 51','Sector 52','Sector 53','Sector 54',
      'Sector 55','Sector 56','Sector 61','Sector 62','Sector 63','Sector 64',
      'Sector 65','Sector 66','Sector 67','Sector 68','Manimajra','Dhanas',
      'Maloya','Kajheri','Raipur Kalan','Khuda Alisher','Khuda Jassu',
      'Mauli Jagran','Sarangpur','Burail','Hallomajra','Daria','Attawa',
      'Bahlana','Kaimbwala','Kishangarh','Palsora','Makhan Majra'
    ]
  },
  {
    state: 'Puducherry',
    cities: [
      'Puducherry','Karaikal','Mahe','Yanam','Ozhukarai','Ariyankuppam',
      'Nettapakkam','Villianur','Bahour','Mannadipet','Thirubuvanai',
      'Oussudu','Mudaliarpet','Lawspet','Reddiarpalayam','Kurumbapet',
      'Muthialpet','White Town','Mission Street','Goubert Avenue',
      'Nehru Street','Mahatma Gandhi Road','Subbaiah Salai','Bharathi Street',
      'Chetty Street','Rue Romain Rolland','Rue de la Caserne','Rue Suffren',
      'Rue Dupleix','Rue Bussy','Bharathi Nagar','Gandhi Nagar','Kamraj Nagar',
      'Thillai Nagar','Rajiv Gandhi Nagar','Indira Nagar','Anna Nagar',
      'Tagore Nagar','Kendra Nagar','Kuyavar Nagar','Saram','Kalapet',
      'Oulgaret','Gorimedu','Ellaipillaichavady','Kosapalayam','Vaithikuppam',
      'Vadhanur','Kottakuppam','Seliamedu','Kirumambakkam','Periyamudaliar Chavadi'
    ]
  },
  {
    state: 'Andaman & Nicobar Islands',
    cities: [
      'Port Blair','Diglipur','Rangat','Mayabunder','Car Nicobar','Campbell Bay',
      'Havelock Island','Neil Island','Bamboo Flat','Prothrapur','Garacharma',
      'Manglutan','Dollygunj','Haddo','Wimberlygunj','Ferrargunj','Chouldari',
      'Billiground','Calicut','Homfreygunj','Nabagram','New Diglipur',
      'Aerial Bay','Ramnagar','Kalighat','Kishori','Uttara','Middle Strait',
      'Baratang','Tirur','Bakultala','Nimbutala','Tugapur','Kadamtala',
      'Sippighat','Ograbraj','Betapur','Jhulastala','Mangrove','Caldera'
    ]
  },
  {
    state: 'Dadra & Nagar Haveli and Daman & Diu',
    cities: [
      'Silvassa','Daman','Diu','Amli','Naroli','Khanvel','Rakholi','Samarvarni',
      'Dadra','Mandoni','Rudana','Vancha','Paria','Vasona','Masat',
      'Galonda','Dudhani','Athal','Sili','Zari','Dabhel','Bhenslore',
      'Ringanwada','Bhimpore','Nani Daman','Moti Daman','Kadaiya','Varkund',
      'Devka','Daman','Vanakbara','Gogola','Bucharwada','Malala','Ghoghla',
      'Fudam','Naida','Milakhdi','Suthri','Kevdi','Bhogat','Chakratirth'
    ]
  },
  {
    state: 'Lakshadweep',
    cities: [
      'Kavaratti','Agatti','Amini','Andrott','Minicoy','Kalpeni','Kiltan',
      'Chetlat','Bitra','Kadmat','Bangaram','Thinnakara','Parali I',
      'Parali II','Cheriyam','Suheli Par'
    ]
  },
]

export const ALL_STATES = INDIA_STATES.map((s) => s.state)

export const ALL_CITIES = INDIA_STATES.flatMap((s) => s.cities)

export const getCitiesByState = (stateName) => {
  const found = INDIA_STATES.find((s) => s.state === stateName)
  return found ? found.cities.slice().sort((a, b) => a.localeCompare(b)) : []
}

export const getStateByCity = (cityName) => {
  const found = INDIA_STATES.find((s) =>
    s.cities.some((c) => c.toLowerCase() === cityName.toLowerCase())
  )
  return found ? found.state : null
}

export const TOP_CITIES = [
  { name: 'Mumbai',     state: 'Maharashtra' },
  { name: 'Delhi',      state: 'Delhi' },
  { name: 'Bengaluru',  state: 'Karnataka' },
  { name: 'Hyderabad',  state: 'Telangana' },
  { name: 'Chennai',    state: 'Tamil Nadu' },
  { name: 'Pune',       state: 'Maharashtra' },
  { name: 'Kolkata',    state: 'West Bengal' },
  { name: 'Ahmedabad',  state: 'Gujarat' },
  { name: 'Jaipur',     state: 'Rajasthan' },
  { name: 'Lucknow',    state: 'Uttar Pradesh' },
  { name: 'Surat',      state: 'Gujarat' },
  { name: 'Chandigarh', state: 'Chandigarh' },
]
